- hosts: master
  become: true
  tasks:

  ## Initialize Kubernetes cluster on master   
    - name: initialize the cluster 
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

  ## Create /.kube directory for storing configuration data
    - name: create .kube directory 
      become: true
      become_user: ansible
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
        
  ## Copy files created by "kubeadm init" to ansible user directory 
    - name: copy admin.conf to user's kube config 
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        remote_src: yes
        owner: ansible

  ## Install flannel network as Pod Networking plugin for Pod communication
    - name: install Pod network 
      become: true
      become_user: ansible
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
