- hosts: master
  become: true
  gather_facts: false
  tasks:
  ## Join k8s worker nodes to the k8s master node by creating tokens in master and then setting join command
    - name: get join command 
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

  ## Join nodes to master
- hosts: workers
  become: yes
  tasks:
    - name: join cluster 
      shell: "{{ hostvars['master'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
